# Generated by Django 4.1.1 on 2022-09-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO "SocialSite_profile" ("firstName", "lastName", "email", "phoneNumber", "bio", "isPrivate")
            VALUES ('Connor', 'Carr-Laughlin', 'cjclmemphis@gmail.com', '9015705688', 'Test', 'False')
            """,
            """
            DELETE FROM "SocialSite_profile" where "lastName"='Carr-Laughlin'
            """
        )
    ]
