# Generated by Django 4.1.1 on 2022-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usersWhoLiked',
            field=models.ManyToManyField(blank=True, related_name='users_who_liked', to='SocialSite.profile'),
        ),
    ]
