# Generated by Django 4.1.1 on 2022-09-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO "SocialSite_profile" ("firstName", "lastName", "email", "phoneNumber", "bio")
            VALUES ('Connor', 'Carr-Laughlin', 'cjclmemphis@gmail.com', '9015705688', 'Lorem Ipsum')
            """, """
                                   DELETE FROM "SocialSite_profile"
                                   WHERE "firstName"='Connor'
                               """
        )
    ]
