# Generated by Django 4.1.1 on 2022-10-10 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0004_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='friendsList',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postList',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usersWhoLiked',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='CommentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SocialSite.comment')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postComment', to='SocialSite.post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
