# Generated by Django 4.1.1 on 2022-10-20 00:02

import SocialSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0007_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=SocialSite.models.get_default_profile_image, max_length=255, null='media/defaultProfileImage.png', upload_to=SocialSite.models.get_profile_image_filepath),
        ),
    ]
