# Generated by Django 4.1.1 on 2022-10-23 19:47

import SocialSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0012_post_is_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=SocialSite.models.get_default_post_image, null=True, upload_to=SocialSite.models.get_profile_image_directory),
        ),
    ]
