# Generated by Django 4.1.1 on 2022-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
