# Generated by Django 4.1.1 on 2022-10-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0015_alter_post_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='textContent',
            new_name='text_content',
        ),
    ]
