# Generated by Django 4.1.1 on 2022-10-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0016_rename_textcontent_post_text_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='numOfLikes',
            new_name='num_of_likes',
        ),
    ]
