# Generated by Django 4.1.1 on 2022-10-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0019_alter_commentlist_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlist',
            name='comments',
        ),
        migrations.AddField(
            model_name='commentlist',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='SocialSite.comment'),
        ),
    ]
