# Generated by Django 4.1.1 on 2022-10-30 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0020_remove_commentlist_comments_commentlist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usersWhoShared',
            field=models.ManyToManyField(blank=True, related_name='users_who_shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
