# Generated by Django 4.1.1 on 2022-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0022_post_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text_content',
        ),
    ]
