# Generated by Django 4.1.1 on 2022-11-27 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0025_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
