# Generated by Django 4.1.1 on 2022-11-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0026_post_tagged_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_users',
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
