# Generated by Django 4.1.1 on 2022-11-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialSite', '0027_remove_post_tagged_users_post_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
